INSERT INTO public.testimonials
  (full_name, birth_date, email, phone, facebook, address, title, before_prayer, after_prayer, current_status, message, media_urls, public_info, status, created_at)
VALUES
(
  'Nguyễn Thị Lan',
  '1985-03-12',
  'lan.nguyen85@gmail.com',
  '+84 912 345 678',
  'facebook.com/lan.nguyen.85',
  'Vietnam',
  'Chúa chữa lành ung thư giai đoạn 3 cho tôi',
  'Năm 2023, tôi được bác sĩ chẩn đoán ung thư vú giai đoạn 3. Tôi hoàn toàn suy sụp, sợ hãi và mất hy vọng. Gia đình tôi cũng rất lo lắng, chồng tôi khóc mỗi đêm. Tôi đã trải qua 4 đợt hóa trị nhưng không có nhiều tiến triển, bác sĩ bắt đầu nói về khả năng sống còn không cao.',
  'Sau khi được cộng đồng HOLYPray cầu nguyện, tôi cảm nhận một sự bình an lạ thường đổ xuống. Ba tháng sau, kết quả xét nghiệm khiến bác sĩ kinh ngạc — các khối u thu nhỏ đáng kể. Sau 6 tháng điều trị tiếp theo, tôi được tuyên bố hoàn toàn sạch bệnh. Bác sĩ gọi đây là "trường hợp ngoài y học".',
  'Tôi hiện tại khỏe mạnh hoàn toàn, đã đi làm lại và tích cực tham gia nhóm cầu nguyện hàng tuần. Tôi dùng câu chuyện của mình để khích lệ những bệnh nhân ung thư khác.',
  'Đừng bao giờ từ bỏ. Dù tình huống có tối tăm đến đâu, Chúa vẫn đang ở đó. Lời cầu nguyện của mọi người đã thực sự thay đổi cuộc đời tôi.',
  '{}',
  true,
  'approved',
  '2026-01-15 08:30:00+00'
),
(
  'Trần Văn Minh',
  '1978-07-22',
  'minhtran78@yahoo.com',
  '+84 903 567 890',
  'facebook.com/minh.tran.pastor',
  'Vietnam',
  'Hôn nhân tan vỡ được phục hồi kỳ diệu',
  'Vợ tôi đã nộp đơn ly hôn sau 15 năm chung sống. Chúng tôi không còn nói chuyện được với nhau, mỗi ngày đều cãi nhau trước mặt các con. Tôi đã nghiện rượu suốt 5 năm và không nhận ra mình đã làm tổn thương gia đình đến mức nào. Vợ tôi đã dọn ra ngoài ở với mẹ ruột.',
  'Sau buổi cầu nguyện, tôi bắt đầu khóc không ngừng — lần đầu tiên trong nhiều năm tôi thực sự nhận ra mình đã sai. Tôi bỏ rượu hoàn toàn từ ngày đó. Vợ tôi nhìn thấy sự thay đổi và quay về nhà sau 3 tháng. Chúng tôi đã làm lễ tái hôn tại nhà thờ vào tháng 12 vừa rồi.',
  'Gia đình chúng tôi hiện rất hạnh phúc. Hai con tôi nói rằng ba chúng trở thành người khác hoàn toàn. Chúng tôi cùng nhau đi nhà thờ mỗi Chủ nhật.',
  'Không có gì là quá trễ với Chúa. Ngay cả hôn nhân tưởng như đã chết cũng có thể được sống lại.',
  '{}',
  true,
  'approved',
  '2026-01-28 14:20:00+00'
),
(
  'Phạm Thị Hương',
  '1992-11-05',
  'huongpham92@gmail.com',
  '+84 976 234 567',
  NULL,
  'Vietnam',
  'Thoát khỏi trầm cảm nặng sau 3 năm',
  'Tôi bị trầm cảm nặng từ năm 2020 sau khi mất việc làm và chia tay người yêu cùng một lúc. Tôi không ra khỏi phòng suốt nhiều tháng, không ăn uống bình thường, từng nghĩ đến việc tự tử nhiều lần. Tôi đã uống thuốc chống trầm cảm nhưng cảm thấy như đang sống mà không thực sự sống.',
  'Khi được cầu nguyện, tôi cảm thấy như một gánh nặng khổng lồ được nhấc khỏi ngực tôi. Tôi ngủ được bình thường lần đầu sau 3 năm. Từ từ tôi bắt đầu muốn ra ngoài, gặp gỡ bạn bè. Sau 2 tháng, bác sĩ tâm thần của tôi đồng ý giảm liều thuốc, và hiện tôi đã ngưng thuốc hoàn toàn.',
  'Tôi đang làm việc trở lại, có một mối quan hệ lành mạnh và đang học thêm để phát triển bản thân. Tôi tham gia nhóm hỗ trợ người trầm cảm để chia sẻ câu chuyện của mình.',
  'Nếu bạn đang ở trong bóng tối, xin hãy biết rằng bạn không đơn độc. Ánh sáng thực sự tồn tại ở phía bên kia.',
  '{}',
  false,
  'approved',
  '2026-02-03 09:15:00+00'
),
(
  'Lê Hoàng Nam',
  '1975-04-18',
  'namlehoang75@gmail.com',
  '+84 908 123 456',
  'facebook.com/lehoangnam75',
  'Vietnam',
  'Công việc kinh doanh phá sản được phục hồi',
  'Công ty tôi phá sản năm 2022 sau đại dịch COVID. Tôi nợ ngân hàng và đối tác hơn 3 tỷ đồng. Nhân viên tôi mất việc, tôi mất nhà, phải đưa vợ con về nhà cha mẹ ở. Tôi xấu hổ đến mức không dám gặp ai, không ngủ được, huyết áp tăng cao.',
  'Sau khi được cầu nguyện cho hoàn cảnh kinh doanh, một người bạn cũ bất ngờ liên lạc và đề nghị hợp tác. Trong 6 tháng chúng tôi xây dựng lại từ đầu. Một năm sau, doanh thu vượt mức trước khi phá sản. Tôi đã trả hết nợ và thuê lại một số nhân viên cũ.',
  'Công ty đang phát triển tốt. Tôi dành 10% lợi nhuận để hỗ trợ các doanh nghiệp nhỏ khác đang gặp khó khăn.',
  'Thất bại không phải là kết thúc. Chúa có thể dùng những lúc thấp nhất của chúng ta để xây dựng một điều gì đó tốt đẹp hơn.',
  '{}',
  true,
  'approved',
  '2026-02-10 16:45:00+00'
),
(
  'Nguyễn Thị Thu Hà',
  '1988-09-30',
  'thuha.nguyen88@gmail.com',
  '+84 934 789 012',
  'facebook.com/thuha.nguyen',
  'Vietnam',
  'Con trai tự kỷ bắt đầu nói chuyện sau lời cầu nguyện',
  'Con trai tôi, bé Khôi, được chẩn đoán tự kỷ nặng lúc 2 tuổi. Đến năm 5 tuổi bé vẫn hoàn toàn không nói được từ nào, không giao tiếp mắt, và thường xuyên nổi cơn hoảng loạn. Tôi đã đưa bé đến mọi trung tâm can thiệp, thử mọi phương pháp nhưng tiến triển rất chậm. Tôi kiệt sức và gần như tuyệt vọng.',
  'Tại buổi cầu nguyện cho bé Khôi, tôi không kỳ vọng nhiều. Nhưng tối hôm đó về nhà, bé nhìn vào mắt tôi và nói "Má". Đây là lần đầu tiên trong 5 năm con tôi gọi tôi. Tôi ôm con mà khóc không thể ngừng. Sau đó bé tiến bộ rất nhanh, hiện đã có thể giao tiếp cơ bản và học hòa nhập.',
  'Bé Khôi giờ 7 tuổi, đang học lớp 1 hòa nhập. Bé có thể trò chuyện ngắn, chơi được với bạn cùng lớp. Giáo viên nói bé tiến bộ vượt bậc.',
  'Đừng bao giờ ngừng cầu nguyện cho con bạn. Chúa yêu những đứa trẻ này hơn cả chúng ta yêu chúng.',
  '{}',
  true,
  'approved',
  '2026-02-18 11:00:00+00'
),
(
  'Võ Đình Phúc',
  '1995-06-14',
  'phucvo95@gmail.com',
  '+84 945 678 901',
  'facebook.com/phucvo.music',
  'Vietnam',
  'Thoát khỏi ma túy sau 7 năm nghiện',
  'Tôi bắt đầu dùng ma túy từ năm 19 tuổi theo bạn bè. Sau 7 năm, tôi đã cai nghiện thất bại 4 lần. Gia đình đã từ bỏ tôi, tôi mất việc, từng ngủ ngoài đường. Tôi biết mình đang chết dần nhưng không thoát ra được. Mỗi lần cai lại tái nghiện trong vòng vài tháng.',
  'Lần này khi được cầu nguyện, tôi trải qua 3 ngày vật vã cai nghiện nhưng cảm giác có ai đó ở bên cạnh suốt. Tôi không tái nghiện. Đây là lần đầu tiên tôi vượt qua được 6 tháng, rồi 1 năm, rồi 2 năm. Gia đình đã đón nhận tôi trở lại.',
  'Tôi đã sạch nghiện được 2 năm 4 tháng. Hiện đang làm việc ổn định và tham gia tình nguyện hỗ trợ người nghiện tại trung tâm cai nghiện địa phương.',
  'Ma túy không phải là con đường không thoát. Tôi là bằng chứng sống. Nếu tôi thoát ra được, bạn cũng có thể.',
  '{}',
  true,
  'approved',
  '2026-02-25 13:30:00+00'
),
(
  'Bùi Thị Xuân Mai',
  '1982-12-08',
  'xuanmai.bui@gmail.com',
  '+84 918 456 789',
  NULL,
  'Vietnam',
  'Vô sinh 8 năm, nay đã có con',
  'Chồng tôi và tôi kết hôn năm 2014. Suốt 8 năm chúng tôi điều trị vô sinh — thử IUI 3 lần thất bại, IVF 2 lần thất bại. Tôi đã chi gần 500 triệu đồng và cạn kiệt cả về tiền bạc lẫn tinh thần. Bác sĩ nói khả năng mang thai tự nhiên của tôi gần như bằng không.',
  'Sau khi dự buổi cầu nguyện chữa lành, tôi không mang nhiều hy vọng vì đã thất vọng quá nhiều rồi. Nhưng 6 tuần sau, que thử thai hiện lên 2 vạch. Tôi cứ nghĩ que hỏng nên thử thêm 5 que nữa. Bác sĩ xác nhận thai 7 tuần khỏe mạnh. Tôi sinh bé trai vào tháng 10 năm 2025.',
  'Bé Ân Điển hiện được 5 tháng tuổi, bụ bẫm và khỏe mạnh. Mỗi ngày nhìn con tôi lại không thể tin đây là sự thật.',
  'Với Chúa không có gì là không thể. 8 năm chờ đợi, nhưng Ngài đúng giờ theo cách của Ngài.',
  '{}',
  false,
  'approved',
  '2026-03-01 07:45:00+00'
),
(
  'Đinh Quốc Hùng',
  '1970-02-25',
  'hungdinh70@gmail.com',
  '+84 901 234 567',
  'facebook.com/dinh.quoc.hung',
  'Vietnam',
  'Tai biến mạch máu não hồi phục hoàn toàn',
  'Tôi bị tai biến vào tháng 3 năm 2024 lúc đang làm việc. Nhập viện cấp cứu, bác sĩ nói tôi may mắn sống sót nhưng liệt nửa người bên trái có thể là vĩnh viễn. Tôi không thể tự ngồi dậy, nói chuyện khó khăn, tay trái hoàn toàn mất cảm giác. Vợ con tôi phải nghỉ việc để chăm sóc tôi.',
  'Sau 3 tháng vật lý trị liệu không tiến triển nhiều, gia đình tôi xin được cầu nguyện. Tuần đầu sau cầu nguyện, tôi bắt đầu cử động được ngón tay trái. Bác sĩ vật lý trị liệu rất ngạc nhiên trước tốc độ phục hồi. Sau 4 tháng tôi đã có thể tự đi lại không cần nạng.',
  'Tôi đã trở lại làm việc bán thời gian. Tay trái phục hồi khoảng 85%. Bác sĩ gọi tôi là "bệnh nhân kỳ diệu" của khoa.',
  'Khi tôi nằm trên giường bệnh không cử động được, lời cầu nguyện của mọi người là điều duy nhất tôi bám vào. Chúa đã không để tôi thất vọng.',
  '{}',
  true,
  'approved',
  '2026-03-08 10:20:00+00'
),
(
  'Lý Thị Ngọc Ánh',
  '1998-08-17',
  'ngocanhly98@gmail.com',
  '+84 962 345 678',
  'facebook.com/ngoc.anh.ly98',
  'Vietnam',
  'Qua được kỳ thi đại học sau 2 lần thất bại',
  'Tôi thi trượt đại học 2 năm liên tiếp dù ôn tập rất nhiều. Gia đình tôi ở quê nghèo, bố mẹ bán ruộng để có tiền cho tôi ôn thi. Áp lực quá lớn khiến tôi bị lo âu nặng, cứ vào phòng thi là quên hết. Sau lần thi thứ hai thất bại, tôi không muốn sống nữa.',
  'Lần thi thứ ba, tôi được cầu nguyện trước kỳ thi một tuần. Tôi vào phòng thi với sự bình tĩnh lạ thường — như có ai đó đang ở bên tôi. Tôi nhớ ra mọi thứ đã học. Kết quả thi của tôi đạt 27.5 điểm, đủ điểm vào ngành Y khoa.',
  'Tôi hiện là sinh viên năm 2 Đại học Y Hà Nội. Tôi muốn trở thành bác sĩ để chữa bệnh cho người nghèo ở quê hương.',
  'Đừng từ bỏ ước mơ của bạn. Đôi khi Chúa để chúng ta chờ để chuẩn bị chúng ta tốt hơn cho điều phía trước.',
  '{}',
  true,
  'approved',
  '2026-03-12 15:10:00+00'
),
(
  'Hoàng Văn Đức',
  '1965-05-03',
  NULL,
  '+84 907 890 123',
  NULL,
  'Vietnam',
  'Chúa hòa giải tôi với người cha 20 năm xa cách',
  'Cha tôi bỏ gia đình khi tôi 12 tuổi. Suốt 20 năm tôi mang trong mình sự giận dữ và oán hận không thể tha thứ. Sự tức giận đó đã ảnh hưởng đến mọi mối quan hệ của tôi — tôi ly hôn 2 lần, không thân thiết được với bất kỳ ai. Tôi biết gốc rễ vấn đề của mình nhưng không thể buông bỏ.',
  'Trong buổi cầu nguyện, tôi khóc lần đầu tiên kể từ năm 12 tuổi. Tôi cảm thấy như có một bức tường đá trong lòng tan ra. Tôi quyết định tìm lại cha. Khi gặp nhau, ông cũng khóc và xin lỗi. Chúng tôi đã ôm nhau lần đầu sau 20 năm. Đó là khoảnh khắc tôi sẽ không bao giờ quên.',
  'Cha tôi và tôi hiện gặp nhau mỗi tháng. Ông đã 78 tuổi và sức khỏe yếu — tôi mừng vì đã kịp hòa giải trước khi quá muộn.',
  'Sự tha thứ không phải là quà tặng bạn dành cho người kia. Đó là quà tặng bạn dành cho chính mình. Tôi đã mất 20 năm để hiểu điều này.',
  '{}',
  false,
  'approved',
  '2026-03-19 08:55:00+00'
);
